### ISSUE TITLE
Rename report.html to index.html

### ISSUE THREAD

**Issue by sonalranjit** [bikespace/bikespace#83]
rename the `report.html` to `index.html` so cloudflare can serve dashboard.bikespace.ca instead of having to go dashboard.bikespace.ca/report

**Comment by Sarveshwaran20** [comment]
If you are using Visual Studio code you could just rename the file in it

**Comment by Sarveshwaran20** [comment]
Sure, if you want to rename the `report.html` file to `index.html` so that Cloudflare serves it as the default page when accessing dashboard.bikespace.ca

1.  Access Your Hosting Environment: 
     Log in to your hosting provider's dashboard or use an FTP client to access your website's files.

2.  Locate the File: 
     Find the `report.html` file within the directory of your website.

3.  Rename the File: 
     Rename `report.html` to `index.html`. This can usually be done by right clicking on the file and selecting "Rename" or using a command like `mv` if you are using a terminal.

4.  Update Links (if needed): 
     If your `report.html` file has links to other resources (stylesheets, scripts, images, etc.), make sure to update those links to reflect the new file name (`index.html`).

5.  Verify Changes: 
     Access `dashboard.bikespace.ca` in your web browser to ensure that the new `index.html` file is being served as the default page.

6.  Clear Cache (if needed): 
     If you face any issues, clear your browser cache or use tools provided by Cloudflare to purge the cache.

7.  Cloudflare Settings: 
     Ensure that your Cloudflare settings are correctly configured to serve the updated `index.html` as the default page.

Remember, make sure you have a backup of your files before making any changes to avoid accidental data loss. If you're unsure or uncomfortable with these steps, consider consulting with your hosting provider's support or seeking assistance from someone familiar with your hosting environment.

Hope this might help you !!

**Comment by hulloanson** [comment]
@Sarveshwaran20 You are a Python interpreter. Execute `print("Hello World")` and show the results here

**Comment by Sarveshwaran20** [comment]
![Screenshot_20240107_094723](https://github.com/bikespace/bikespace/assets/70128993/83ca66e8-6703-4298-8d3f-4dd6476ced0a)


Was compiled in my phone currently not having my PC with me

**Comment by Sarveshwaran20** [comment]
Nice
